name: Release

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "SemVer Increment"
        required: true
        default: "minor"
        type: choice
        options:
          - patch
          - minor
          - major
      summary:
        description: "Please enter a summary for this change (this will be in the changelogs)"
        required: true
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install deps
      - run: npm ci

      - name: Creates changeset
        run: |
          node ./scripts/version.cjs --semvar-increment=${{ inputs.increment }} --summary=${{ inputs.summary }}
        env:
          GITHUB_TOKEN: ${{ secrets.READ_ONLY_GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.READ_ONLY_GITHUB_TOKEN }}
